// Generated by CoffeeScript 1.9.3
(function() {
  window.muro3 = window.muro3 || {};

  window.muro3.config = {
    width: 800,
    height: 600,
    fps: 30
  };

  window.muro3.manifest = [
    {
      src: "assets/omino.png",
      id: "playerStanding"
    }, {
      src: "assets/bg.png",
      id: "bg"
    }, {
      src: "assets/ominocharged.png",
      id: "playerCharged"
    }, {
      src: "assets/ladder.png",
      id: "ladder"
    }, {
      src: "assets/zombie.png",
      id: "zombie"
    }, {
      src: "assets/stone.png",
      id: "stone"
    }
  ];

}).call(this);
