// Generated by CoffeeScript 1.6.1
(function() {
  var _this = this;

  window.muro3 = window.muro3 || {};

  window.muro3.Game = (function() {

    function Game(canvas, stage) {
      var remainder,
        _this = this;
      this.canvas = canvas;
      this.stage = stage;
      this.init = function() {
        return Game.prototype.init.apply(_this, arguments);
      };
      this.addZombie = function() {
        return Game.prototype.addZombie.apply(_this, arguments);
      };
      this.gameTick = function(delta, current) {
        return Game.prototype.gameTick.apply(_this, arguments);
      };
      this.keyToAction = function(e) {
        return Game.prototype.keyToAction.apply(_this, arguments);
      };
      this.touchToAction = function(touch) {
        return Game.prototype.touchToAction.apply(_this, arguments);
      };
      this.drawScore = function() {
        return Game.prototype.drawScore.apply(_this, arguments);
      };
      this.gameOver = function() {
        return Game.prototype.gameOver.apply(_this, arguments);
      };
      this.scaleDisplay = function() {
        return Game.prototype.scaleDisplay.apply(_this, arguments);
      };
      this.config = window.muro3.config;
      this.colWidth = Math.floor(this.config.width / 13);
      remainder = this.config.width % 13;
      this.leftMargin = Math.floor(remainder / 2);
      this.scaleInfo = {
        ratio: 1,
        currentWidth: 0,
        currentHeight: 0
      };
      this.ladderPositions = [2, 5, 7, 9];
      this.scoreDisplay = new createjs.Text("", "bold 17px Arial", "#000000");
      this.scoreDisplay.x = 20;
      this.scoreDisplay.y = 3;
      this.stage.addChild(this.scoreDisplay);
      this.scaleDisplay();
      window.addEventListener("resize", this.scaleDisplay, false);
      this.shoot = false;
      this.moveLeft = false;
      this.moveRight = false;
      createjs.Ticker.useRAF = true;
      createjs.Ticker.setFPS(this.config.fps);
    }

    Game.prototype.scaleDisplay = function() {
      this.scaleInfo.currentWidth = window.innerWidth;
      this.scaleInfo.currentHeight = this.scaleInfo.currentWidth * (this.config.height / this.config.width);
      if (this.scaleInfo.currentHeight > window.innerHeight) {
        this.scaleInfo.currentHeight = window.innerHeight;
        this.scaleInfo.currentWidth = this.scaleInfo.currentHeight * (this.config.width / this.config.height);
      }
      this.canvas.style.width = this.scaleInfo.currentWidth + 'px';
      return this.canvas.style.height = this.scaleInfo.currentHeight + 'px';
    };

    Game.prototype.getXPos = function(position) {
      return this.leftMargin + (position * this.colWidth);
    };

    Game.prototype.gameOver = function() {
      alert("Game Over. Hai fatto " + this.score + " punti");
      return this.init();
    };

    Game.prototype.drawScore = function() {
      return this.scoreDisplay.text = "Punteggio: " + this.score;
    };

    Game.prototype.touchToAction = function(touch) {
      var middleX, middleY;
      middleX = this.scaleInfo.currentWidth / 2;
      middleY = this.scaleInfo.currentHeight / 2;
      if (touch.pageY < middleY) {
        this.moveLeft = false;
        this.moveRight = false;
        this.shoot = true;
      } else {
        if (touch.pageX > middleX) {
          this.shoot = false;
          this.moveLeft = false;
          this.moveRight = true;
        } else {
          this.shoot = false;
          this.moveRight = false;
          this.moveLeft = true;
        }
      }
      return false;
    };

    Game.prototype.keyToAction = function(e) {
      switch (e.keyCode) {
        case 37:
          this.moveLeft = true;
          this.moveRight = false;
          break;
        case 39:
          this.moveRight = true;
          this.moveLeft = false;
          break;
        case 32:
          this.shoot = true;
          break;
        case 80:
          createjs.Ticker.setPaused(!createjs.Ticker.getPaused());
      }
      return false;
    };

    Game.prototype.gameTick = function(delta, current) {
      var newStones, newZombies, nstone, stone, zombie, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _m, _ref, _ref1, _ref2, _ref3, _ref4;
      if (this.player.position === 0 || this.player.position === 12) {
        this.player.charge();
        this.shoot = false;
      }
      if (this.moveRight && this.player.position < 12) {
        this.player.position += 1;
        this.moveRight = false;
      }
      if (this.moveLeft && this.player.position > 0) {
        this.player.position -= 1;
        this.moveLeft = false;
      }
      if (this.shoot && this.player.charged) {
        this.player.uncharge();
        nstone = new window.muro3.Stone(this.player.position, this.stage, this.assets);
        this.stones.push(nstone);
        nstone.drawing.x = this.getXPos(nstone.position) + 20;
        this.shoot = false;
      }
      if (Math.random() < 0.02) {
        this.addZombie(this.ladderPositions);
      }
      this.player.update();
      this.player.drawing.y = 34;
      this.player.drawing.x = this.getXPos(this.player.position);
      _ref = this.zombies;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        zombie = _ref[_i];
        zombie.update();
        if (zombie.drawing.y < 100) {
          this.gameOver();
        }
      }
      _ref1 = this.stones;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        stone = _ref1[_j];
        stone.update();
        if (stone.drawing.y > 600) {
          stone.toRemove = true;
        }
        _ref2 = this.zombies;
        for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
          zombie = _ref2[_k];
          if (stone.position === zombie.position && (stone.drawing.y - zombie.drawing.y) > 0) {
            zombie.toRemove = true;
            stone.toRemove = true;
            this.score++;
          }
        }
      }
      newStones = [];
      _ref3 = this.stones;
      for (_l = 0, _len3 = _ref3.length; _l < _len3; _l++) {
        stone = _ref3[_l];
        if (stone.toRemove) {
          this.stage.removeChild(stone.drawing);
        } else {
          newStones.push(stone);
        }
      }
      newZombies = [];
      _ref4 = this.zombies;
      for (_m = 0, _len4 = _ref4.length; _m < _len4; _m++) {
        zombie = _ref4[_m];
        if (zombie.toRemove) {
          this.stage.removeChild(zombie.drawing);
        } else {
          newZombies.push(zombie);
        }
      }
      this.stones = newStones;
      this.zombies = newZombies;
      this.drawScore(this.score);
      return this.stage.update();
    };

    Game.prototype.addZombie = function() {
      var newzombie, position;
      position = this.ladderPositions[Math.floor(Math.random() * this.ladderPositions.length)];
      newzombie = new window.muro3.Zombie(position, this.stage, this.assets);
      newzombie.drawing.x = this.getXPos(position);
      return this.zombies.push(newzombie);
    };

    Game.prototype.init = function() {
      var addLadder, position, preventDefault, _i, _len, _ref,
        _this = this;
      this.assets = window.muro3.assets;
      console.dir(this.assets);
      this.stage.clear();
      this.zombies = [];
      this.stones = [];
      this.score = 0;
      this.stage.addChild(new createjs.Bitmap(this.assets.bg));
      this.player = new window.muro3.Player(this.stage, this.assets);
      this.player.addToStage();
      addLadder = function(position) {
        var newLadder;
        newLadder = _this.stage.addChild(new createjs.Bitmap(_this.assets.ladder));
        newLadder.x = _this.getXPos(position);
        return newLadder.y = 110;
      };
      _ref = this.ladderPositions;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        position = _ref[_i];
        addLadder(position);
      }
      document.onkeydown = this.keyToAction;
      preventDefault = function(e) {
        return e.preventDefault();
      };
      window.addEventListener('touchmove', preventDefault);
      window.addEventListener('touchend', preventDefault);
      window.addEventListener('click', function(e) {
        e.preventDefault();
        _this.touchToAction(e);
        return false;
      });
      window.addEventListener('touchstart', function(e) {
        e.preventDefault();
        _this.touchToAction(e.touches[0]);
        return false;
      });
      createjs.Ticker.removeAllListeners();
      return createjs.Ticker.addListener(this.gameTick);
    };

    return Game;

  })();

}).call(this);
