// Generated by CoffeeScript 1.6.1
(function() {

  window.muro3 = window.muro3 || {};

  window.muro3.load = function(canvas, stage, oncomplete) {
    var config, loadingText, manifest, preload;
    config = window.muro3.config;
    manifest = window.muro3.manifest;
    loadingText = new createjs.Text("Loading", "bold 24px Arial", "#000000");
    loadingText.y = 50;
    loadingText.x = canvas.width / 3;
    stage.addChild(loadingText);
    stage.update();
    preload = new createjs.PreloadJS();
    window.muro3.assets = {};
    preload.onFileLoad = function(e) {
      var newImg;
      switch (e.type) {
        case createjs.PreloadJS.IMAGE:
          newImg = new Image();
          newImg.src = e.src;
          return window.muro3.assets[e.id] = newImg;
      }
    };
    preload.onComplete = oncomplete;
    return preload.loadManifest(manifest);
  };

}).call(this);
