// Generated by CoffeeScript 1.9.3
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.muro3.Player = (function() {
    function Player(stage, assets) {
      this.stage = stage;
      this.uncharge = bind(this.uncharge, this);
      this.charge = bind(this.charge, this);
      this.update = bind(this.update, this);
      this.addToStage = bind(this.addToStage, this);
      this.standingBitmap = new createjs.Bitmap(assets.playerStanding);
      this.chargedBitmap = new createjs.Bitmap(assets.playerCharged);
      this.position = 1;
      this.charged = false;
      this.previousState = "standing";
    }

    Player.prototype.addToStage = function() {
      return this.drawing = this.stage.addChild(this.standingBitmap);
    };

    Player.prototype.update = function() {
      if (this.charged && this.previousState === "standing") {
        this.stage.removeChild(this.drawing);
        this.drawing = this.stage.addChild(this.chargedBitmap);
        this.previousState = "charged";
      }
      if (!this.charged && this.previousState === "charged") {
        this.stage.removeChild(this.drawing);
        this.drawing = this.stage.addChild(this.standingBitmap);
        return this.previousState = "standing";
      }
    };

    Player.prototype.charge = function() {
      return this.charged = true;
    };

    Player.prototype.uncharge = function() {
      return this.charged = false;
    };

    return Player;

  })();

}).call(this);
