// Generated by CoffeeScript 1.6.1
(function() {
  var _this = this;

  window.muro3.Player = (function() {

    function Player(stage, assets) {
      var _this = this;
      this.stage = stage;
      this.uncharge = function() {
        return Player.prototype.uncharge.apply(_this, arguments);
      };
      this.charge = function() {
        return Player.prototype.charge.apply(_this, arguments);
      };
      this.update = function() {
        return Player.prototype.update.apply(_this, arguments);
      };
      this.addToStage = function() {
        return Player.prototype.addToStage.apply(_this, arguments);
      };
      this.standingBitmap = new createjs.Bitmap(assets.playerStanding);
      this.chargedBitmap = new createjs.Bitmap(assets.playerCharged);
      this.position = 1;
      this.charged = false;
      this.previousState = "standing";
    }

    Player.prototype.addToStage = function() {
      return this.drawing = this.stage.addChild(this.standingBitmap);
    };

    Player.prototype.update = function() {
      if (this.charged && this.previousState === "standing") {
        this.stage.removeChild(this.drawing);
        this.drawing = this.stage.addChild(this.chargedBitmap);
        this.previousState = "charged";
      }
      if (!this.charged && this.previousState === "charged") {
        this.stage.removeChild(this.drawing);
        this.drawing = this.stage.addChild(this.standingBitmap);
        return this.previousState = "standing";
      }
    };

    Player.prototype.charge = function() {
      return this.charged = true;
    };

    Player.prototype.uncharge = function() {
      return this.charged = false;
    };

    return Player;

  })();

}).call(this);
