// Generated by CoffeeScript 1.9.3
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.muro3.Stone = (function() {
    function Stone(position, stage, assets) {
      this.update = bind(this.update, this);
      this.position = position;
      this.drawing = stage.addChild(new createjs.Bitmap(assets.stone));
      this.drawing.y = 95;
    }

    Stone.prototype.update = function() {
      return this.drawing.y += 2;
    };

    return Stone;

  })();

}).call(this);
