// Generated by CoffeeScript 1.6.1
(function() {
  var _this = this;

  window.muro3.Stone = (function() {

    function Stone(position, stage, assets) {
      var _this = this;
      this.update = function() {
        return Stone.prototype.update.apply(_this, arguments);
      };
      this.position = position;
      this.drawing = stage.addChild(new createjs.Bitmap(assets.stone));
      this.drawing.y = 95;
    }

    Stone.prototype.update = function() {
      return this.drawing.y += 2;
    };

    return Stone;

  })();

}).call(this);
