// Generated by CoffeeScript 1.9.3
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.muro3.Zombie = (function() {
    function Zombie(position, stage, assets) {
      this.position = position;
      this.update = bind(this.update, this);
      this.drawing = stage.addChild(new createjs.Bitmap(assets.zombie));
      this.speed = (Math.random() * 1) + 0.5;
      this.drawing.y = 560;
    }

    Zombie.prototype.update = function() {
      return this.drawing.y -= this.speed;
    };

    return Zombie;

  })();

}).call(this);
