// Generated by CoffeeScript 1.6.1
(function() {
  var _this = this;

  window.muro3.Zombie = (function() {

    function Zombie(position, stage, assets) {
      var _this = this;
      this.position = position;
      this.update = function() {
        return Zombie.prototype.update.apply(_this, arguments);
      };
      this.drawing = stage.addChild(new createjs.Bitmap(assets.zombie));
      this.speed = (Math.random() * 1) + 0.5;
      this.drawing.y = 560;
    }

    Zombie.prototype.update = function() {
      return this.drawing.y -= this.speed;
    };

    return Zombie;

  })();

}).call(this);
